---
#- name: Update and upgrade yum packages
#  become: true
#  yum:
#    name: "*"
#    state: latest
- name: Copy K8s repo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
  - {src: "files/kubernetes.repo", dest: "/etc/yum.repos.d/kubernetes.repo"}
  - {src: "files/docker.repo", dest: "/etc/yum.repos.d/docker.repo"}
- name: Update repositories cache and install needed packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - containerd.io
  - docker-compose-plugin
  - kubeadm
  - kubelet
  register: result
  until: result is not failed
  retries: 3
  delay: 3
- name: create /etc/containerd
  file:
    path: /etc/containerd
    state: directory
- name: Copy containerd config
  copy:
    src: files/containerd-config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: restart containerd
- name: flush_handlers
  meta: flush_handlers
