---
- name: Set a hostname
  hostname:
    name: "{{ inventory_hostname }}"
- name: Set timezone to Africa/Cairo
  timezone:
    name: Africa/Cairo
- stat: path=/etc/selinux/config
  register: selinuxfile
- name: replacing Enforcing into Disabled SElinux
  lineinfile:
    path: /etc/selinux/config
    regexp: 'SELINUX=enforcing'
    line: 'SELINUX=disabled'
    backrefs: yes
  when: selinuxfile.stat.exists
  notify: Disable SELinux
- name: flush_handlers
  meta: flush_handlers

- name: Disable swap
  lineinfile:
    path: /etc/fstab
    regexp: '\W*(swap)\W*'
    state:  absent
  notify: swapoff
- name: flush_handlers
  meta: flush_handlers
- name: adjust hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
  with_items:
  - "{{ groups['haproxy-keepalive'] }}"
  - "{{ groups['masters'] }}"
  - "{{ groups['etcd'] }}"
  - "{{ groups['workers'] }}"
- name: start firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes
- name: firewall configuration
  firewalld:
    port: "{{ item }}"
    state:  enabled
    permanent:  yes
  notify: firewall-reload
  loop: "{{ ports }}"



