---
apiVersion: "kubeadm.k8s.io/v1beta3"
kind: InitConfiguration
nodeRegistration:
    name: etcd-03
localAPIEndpoint:
    advertiseAddress: 192.168.160.4
---
apiVersion: "kubeadm.k8s.io/v1beta3"
kind: ClusterConfiguration
etcd:
    local:
        serverCertSANs:
        - 192.168.160.4
        peerCertSANs:
        - 192.168.160.4
        extraArgs:
            initial-cluster: etcd-01=https://192.168.160.2:2380,https://192.168.160.3:2380,https://192.168.160.4:2380
            initial-cluster-state: new
            name: etcd-03
            listen-peer-urls: https://192.168.160.4:2380
            listen-client-urls: https://192.168.160.4:2379
            advertise-client-urls: https://192.168.160.4:2379
            initial-advertise-peer-urls: https://192.168.160.4:2380
